### ISSUE TITLE
Reflection Exception Error

### ISSUE THREAD

**Issue by IntegrityFoundation** [Faryshta/yii2-disable-submit-buttons#2]
I installed the widget using composer and I entered  'faryshta\assets\ActiveFormDisableSubmitButonsAsset', in $depends property in AppAsset file.

But there is error as:

ReflectionException
Class faryshta\assets\ActiveFormDisableSubmitButonsAsset does not exist

**Comment by Faryshta** [comment]
there was an error on the doc, it said 'Butons' instead of 'Buttons'.

Fixed in https://github.com/Faryshta/yii2-disable-submit-buttons/commit/6f1e38ae6609cab3d8a9773a26a10bf7cca74f80
