### ISSUE TITLE
remove disable button when a validation fails

### ISSUE THREAD

**Issue by omar-mostro** [Faryshta/yii2-disable-submit-buttons#5]
Hello.

I have some fields that are required, so when that field is empty and the user submit the form a yii validation show a message with a field cant be empty, but with this plugin the submit button stills disable and i can´t send again the form

**Comment by Faryshta** [comment]
The plugin is supposed to re enable the submit button if validation fails. How are you declaring your submit button and your form?

**Comment by Faryshta** [comment]
fixed in #6
